FROM ibmcom/websphere-liberty:latest
USER root:root
RUN yum -y install git
RUN yum -y install wget
RUN yum -y install unzip 
RUN git clone https://github.com/IBM/spm-kubernetes
RUN mkdir -p /opt/ant \
    && cd /opt/ant \
    && wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.zip \
    && unzip -x apache-ant-1.10.6-bin.zip
ENV ANT_HOME=/opt/ant/apache-ant-1.10.6
ENV PATH=${PATH}:$ANT_HOME/bin
RUN mkdir -p /opt/dependencies
COPY j2ee.jar /opt/dependencies
ENV J2EE_JAR=/opt/dependencies/j2ee.jar 
